import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="p-4">
          <div className="flex justify-between items-center max-w-6xl mx-auto">
            <ul className="flex gap-4 ">
              <Link href='/'><li>Home</li></Link>
              <Link href='/profile'><li>Profile</li></Link>
            </ul>
            <div className="flex gap-4">
              <Link href='/login'><button>Login</button></Link>
              <Link href='/logout'><button>Logout</button></Link>
            </div>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
